spring:
  application:
    name: finance-user
  profiles:
    active: dev

server:
  port: 9030
  context-path: /user

management:
  security:
    enabled: false

feign:
  hystirx:
    enable: true

eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/

security:
  oauth2:
    resource:
      id: finance-user
      user-info-uri: http://localhost:8080/uaa/user
      prefer-token-info: false