server:
  port: 8080

management:
  security:
    enabled: false

spring:
  application:
    name: finance-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

zuul:
  ignored-services: '*'
  routes:
    uaa:
      path: /uaa/**
      serviceId: finance-auth-server
      sensitiveHeaders:
      strip-prefix: false

    ribbon-user:
      path: /ribbon-user/**
      serviceId: finance-ribbon-user
      sensitiveHeaders:
      strip-prefix: false

    user:
      path: /user/**
      serviceId: finance-user
      sensitiveHeaders:
      strip-prefix: false

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:8080/uaa/user
      prefer-token-info: false
  add-proxy-headers: true



