eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

spring:
  application:
    name: eureka-song
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.11.120:3306/zjg_finance?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: dev@xlh.com
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update

#  #配置redis数据库连接
#  redis:
#    host: 172.16.11.70
#    port: 6379
#    pool:
#      max-idle: 20
#      min-idle: 1
#      max-active: 20
#      max-wait: 60000
#      database: 0 #默认是索引为的0的数据库

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    suffix: .html

server:
  port: 8080



