spring:
  application:
    name: finance-com.easyrong.wireless.financegateway.config-server
  profiles:
      active: dev
  cloud:
    com.easyrong.wireless.financegateway.config:
      server:
        git:
          uri: https://github.com/gitroc/com.easyrong.wireless.financegateway.config-git.git
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 9002
management:
  security:
    enabled: false